apiVersion: v1
kind: PersistentVolume
metadata:
  name: task-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/mnt/data"


---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: task-pv-claim
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 512Mi


---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: my-app-volume
spec:
  selector:
    matchLabels:
      app: mypod
  serviceName:  "my-frontend"
  replicas: 2
  template:
    metadata:
      labels:
        app: mypod
    spec:
      volumes:
      - name: task-pv-storage
        persistentVolumeClaim:
          claimName: task-pv-claim
      containers:
      - name: my-frontend
        image: nginx
        ports:
          - containerPort: 80
            name: "http-server"
        volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: task-pv-storage
  # esto es para cuando se trabaja con proveedores de cloud. Ej: AWS, GCP, AZURE, etc.
 # volumeClaimTemplates:
  #- metadata:
   #   name: csi-pvc
    #spec:
     # storageClassName: manual
      #accessModes:
      #- ReadWriteOnce
      #hostPath: # aplica a cluster de un solo nodo como minikube, para desarrollo.
       #  path: "/mnt/data"
      #resources:
       # requests:
        #  storage: 3Gi
